import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState, useEffect } from "react";
import axios from 'axios';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [predictions, setPredictions] = useState({ fnn: -1, llm: -1, lr: -1, xgb: -1 });
  const [loading, setLoading] = useState(false);

  const [input, setInput] = useState('');

  const runPythonScript = async () => {
    try {
      setLoading(true);
      console.log(input); // Utilisation de console.log au lieu de print
      const response = await axios.get("http://127.0.0.1:8000/get_prediction", { params: { text: input } }); // Utilisation de params au lieu de data
      console.log(response.data);

      if (response.data.xgb == [0]) {
        response.data.xgb = 0;
      }


      const parsedData = {
        fnn: response.data.fnn,
        llm: response.data.xgb,
        lr: response.data.lr,
        xgb: response.data.xgb,
      };

      setPredictions(parsedData);
      console.log("Predictions State:", parsedData);

      setLoading(false);
    } catch (error) {
      console.error("Erreur lors de la récupération des prédictions :", error);
      setLoading(false);
    }
  };

  const handleButtonClick = () => {
    runPythonScript();
  };

  const getModelLabel = (value) => {
    if (Array.isArray(value)) {
      return value[0] === 0 ? "ChatGPT" : "Humain";
        }
    return value === 0 ? "ChatGPT" : "Humain";
  };

  const getCardColor = (value) => {
    return value === -1 ? '' : (value === 0 ? styles.redCard : styles.greenCard);
  };

  const handleChange = (event) => {
    setInput(event.target.value);
  };

  return (
      <>
        <Head>
          <title>Hackathon IA DATA - IA VS AI</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/img/favicon.ico" />
        </Head>
        <main className={`${styles.main}`}>
          <div className={styles.navbar}>
            <div className={styles.navbarleft}>
              <Image
                  src="/img/logominarm.jpg"
                  alt=" "
                  width={100}
                  height={100}
                  className={styles.logominarm}
              />
              <p className={styles.text}>Hackathon IA DATA - IA VS AI</p>
            </div>
            <div className={styles.navbarright}>
              <Image
                  src="/img/logohack.png"
                  alt=" "
                  width={71}
                  height={71}
                  className={styles.logohack}
              />
            </div>
          </div>
          <div className={styles.containercards}>
            {Object.entries(predictions).map(([model, value]) => (
                <div key={model} className={`${styles.card} ${getCardColor(value)} ${loading ? styles.loading : styles.loaded}`}>
                  <p>{model.toUpperCase()}</p>
                  {value !== -1 && <p>{getModelLabel(value)}</p>}
                </div>
            ))}
          </div>
          <div className={styles.containersearch}>
            <div className={styles.searchbar}>
              <input id="searchInput" type="text" placeholder="Write a text..." className={styles.inputSearch} value={input} onChange={handleChange} />
              <Image
                  src="/img/logohack.png"
                  alt=" "
                  width={50}
                  height={50}
                  className={styles.searchicon}
              />
            </div>


          </div>
          <div className={styles.buttonContainer}>
            <button className={styles.computeButton} onClick={handleButtonClick}>COMPUTE &gt;</button>
          </div>
        </main>
      </>
  );
}
