import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState, useEffect } from "react";
import { exec } from 'child_process';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [percentages, setPercentages] = useState([null, null, null, null]);
  const [loading, setLoading] = useState(false); // Nouvel état pour gérer le chargement
  const [output, setOutput] = useState('');

  const loadData = () => {
    setLoading(true); // Marquez le début du chargement
    const loadedPercentages = [70, 85, 60, 95]; // Exemple de pourcentages chargés
    setPercentages(loadedPercentages);
    setTimeout(() => setLoading(false), 1000); // Marquez la fin du chargement après une seconde (simulation)
  };

  const runPythonScript = async () => {
    const child_process = require('child_process');
    const util = require('util');
    const execAsync = util.promisify(child_process.exec);
  
    try {
      const { stdout, stderr } = await execAsync('python3 testHW.py');
      console.log('Résultat du script Python :', stdout);
      if (stderr) {
        console.error('Erreur lors de l\'exécution du script Python :', stderr);
      }
    } catch (error) {
      console.error('Une erreur s\'est produite lors de l\'exécution du script Python :', error);
    }
  };
  
  //runPythonScript();
  

  // À l'intérieur de votre composant Home, utilisez cette fonction lors du clic sur le bouton
  const handleButtonClick = () => {
    //const inputValue = document.getElementById('searchInput').value;
    runPythonScript();
  };

  return (
    <>
      <Head>
        <title>Hackathon IA DATA - IA VS AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        
        <div className={styles.navbar}>
          <div className={styles.navbarleft}>
            <Image
              src="/logominarm.jpg"
              alt="Minarm Logo"
              width={100}
              height={100}
              className={styles.logominarm}
            />
            <p className={styles.text}>Hackathon IA DATA - IA VS AI</p>
          </div>
          <div className={styles.navbarright}>
            <Image
              src="/logohack.png"
              alt="Minarm Logo"
              width={71}
              height={71}
              className={styles.logohack}
            />
          </div>
        </div>

        <div className={styles.containercards}>
          <div className={`${styles.card} ${loading ? styles.loading : styles.loaded}`}>
            <p>XGB</p>
            {percentages[0] !== null && <p>{percentages[0]}%</p>}
          </div>
          <div className={`${styles.card} ${loading ? styles.loading : styles.loaded}`}>
            <p>LR</p>
            {percentages[1] !== null && <p>{percentages[1]}%</p>}
          </div>
          <div className={`${styles.card} ${loading ? styles.loading : styles.loaded}`}>
            <p>LLM</p>
            {percentages[2] !== null && <p>{percentages[2]}%</p>}
          </div>
          <div className={`${styles.card} ${loading ? styles.loading : styles.loaded}`}>
            <p>FNN</p>
            {percentages[3] !== null && <p>{percentages[3]}%</p>}
          </div>
        </div>

        <div className={styles.containersearch}>
          <div className={styles.searchbar}>
            <input id="searchInput" type="text" placeholder="Write a text..." className={styles.inputSearch} />
            <Image
              src="/logohack.png"
              alt="Minarm Logo"
              width={50}
              height={50}
              className={styles.searchicon}
            />
          </div>
        </div>

        <div className={styles.buttonContainer}>
          <button className={styles.computeButton} onClick={handleButtonClick}>COMPUTE &gt;</button>
          <div>Résultat : {output}</div>
        </div>

      </main>
    </>
  );
}
